-- Every notification in this app until now has been reactive -- someone
-- replied to your post, someone liked it, an admin broadcast something.
-- None of that brings back a student who has nothing of their own to be
-- notified about. This adds three scheduled, content-driven notification
-- types (a daily Buzz digest, a new-listings digest, and an inactivity
-- win-back), the same "system notification, no actor" shape as
-- admin_broadcast, generated by pg_cron directly in Postgres rather than
-- an external scheduler -- consistent with this project's existing
-- SQL-native approach to background jobs, and it means these digests
-- automatically get push-dispatched too (they're just more rows in
-- notifications, so the existing dispatch_push_notification trigger
-- fires for them exactly like any other notification).

create extension if not exists pg_cron;

-- =========================================================================
-- 1. notifications.type grows three values.
-- =========================================================================

alter table public.notifications drop constraint if exists notifications_type_check;
alter table public.notifications add constraint notifications_type_check
  check (type in (
    'buzz_reply',
    'buzz_like',
    'buzz_pin',
    'hostel_update',
    'admin_report',
    'welcome',
    'admin_broadcast',
    'buzz_digest',
    'new_listings_digest',
    'winback'
  ));

-- =========================================================================
-- 2. Per-user dedup tracking + activity tracking (profiles).
-- =========================================================================
-- Three separate "last sent" columns rather than a shared tracking table
-- -- each digest has its own independent cadence, and this keeps every
-- query a plain indexed column comparison.

alter table public.profiles add column if not exists last_buzz_digest_sent_at timestamptz;
alter table public.profiles add column if not exists last_listings_digest_sent_at timestamptz;
alter table public.profiles add column if not exists last_winback_sent_at timestamptz;

-- Deliberately NOT auth.users.last_sign_in_at -- that only updates on an
-- actual sign-in event, not on general app usage within an existing
-- session, and reading auth.users directly from a function owned by a
-- non-superuser role is its own can of worms. This is a plain
-- self-reported "the app was open" timestamp instead, touched once per
-- session by the client (see AuthProvider), same posture as the
-- analytics identifyUser() call it sits next to.
alter table public.profiles add column if not exists last_active_at timestamptz;

create or replace function public.touch_last_active()
returns void
language sql
security invoker
set search_path = public
as $$
  update public.profiles set last_active_at = now() where id = auth.uid();
$$;

grant execute on function public.touch_last_active() to authenticated;
-- Harmless as a no-op either way (auth.uid() is null for anon, matching
-- no row), but PostgREST grants EXECUTE to the PUBLIC pseudo-role by
-- default on a newly created function, and every role -- including anon
-- -- inherits access through that regardless of its own individual
-- grants. Revoking from just "anon" doesn't touch it (this was tried and
-- confirmed to NOT work); "public" here is the pseudo-role, not the
-- schema. Explicitly revoking from PUBLIC keeps this consistent with
-- every other authenticated-only RPC in this project, which reject an
-- anon caller outright rather than silently succeeding and doing nothing.
revoke execute on function public.touch_last_active() from public;

-- =========================================================================
-- 3. Daily Buzz digest -- only fires if there's been real new activity.
-- =========================================================================

create or replace function public.send_buzz_digest()
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  v_new_post_count integer;
  v_count integer;
begin
  select count(*) into v_new_post_count
  from public.buzz_posts
  where created_at > now() - interval '24 hours';

  -- Not enough new content to be worth a notification -- a quiet day
  -- shouldn't still ping everyone.
  if v_new_post_count < 3 then
    return 0;
  end if;

  insert into public.notifications (recipient_id, type, title, body, actor_id, actor_name, link_url)
  select
    p.id,
    'buzz_digest',
    '🔥 ' || v_new_post_count || ' new posts on Buzz today',
    'See what students are talking about.',
    null,
    'Campa',
    '/buzz'
  from public.profiles p
  where not p.is_suspended
    and (p.last_buzz_digest_sent_at is null or p.last_buzz_digest_sent_at < now() - interval '20 hours');

  get diagnostics v_count = row_count;

  update public.profiles
  set last_buzz_digest_sent_at = now()
  where not is_suspended
    and (last_buzz_digest_sent_at is null or last_buzz_digest_sent_at < now() - interval '20 hours');

  return v_count;
end;
$$;

-- 18:00 UTC -- Ghana is UTC+0 year-round (no DST), so this lands as a
-- 6pm check-in, a natural "see what happened today" moment.
select cron.schedule(
  'buzz-digest-daily',
  '0 18 * * *',
  $$select public.send_buzz_digest()$$
);

-- Deliberately never granted to anon/authenticated, unlike every other
-- security definer RPC in this project -- this one has no internal
-- has_permission() check at all (it isn't gated per-caller, it just
-- blasts every non-suspended user), so it must never be directly
-- callable via PostgREST. It's only ever invoked by pg_cron above, which
-- runs inside Postgres itself and never goes through PostgREST/RLS. The
-- explicit revoke is redundant with Supabase's own project-wide default
-- (new functions aren't PUBLIC-executable unless granted) but stated
-- here anyway so this is obviously intentional, not a forgotten grant.
revoke execute on function public.send_buzz_digest() from public, anon, authenticated;

-- =========================================================================
-- 4. New marketplace listings digest.
-- =========================================================================
-- Only counts status='active' listings -- while the marketplace is still
-- pre-launch (see 20260731300000-era pending_launch work), nothing here
-- fires at all, which is correct: there's nothing live yet to tell
-- anyone about.

create or replace function public.send_new_listings_digest()
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  v_new_listing_count integer;
  v_count integer;
begin
  select count(*) into v_new_listing_count
  from public.market_listings
  where status = 'active' and created_at > now() - interval '24 hours';

  if v_new_listing_count < 1 then
    return 0;
  end if;

  insert into public.notifications (recipient_id, type, title, body, actor_id, actor_name, link_url)
  select
    p.id,
    'new_listings_digest',
    '🛍️ ' || v_new_listing_count || ' new ' || (case when v_new_listing_count = 1 then 'item' else 'items' end) || ' on the Marketplace',
    'Textbooks, furniture, and more from fellow students.',
    null,
    'Campa',
    '/market'
  from public.profiles p
  where not p.is_suspended
    and (p.last_listings_digest_sent_at is null or p.last_listings_digest_sent_at < now() - interval '20 hours');

  get diagnostics v_count = row_count;

  update public.profiles
  set last_listings_digest_sent_at = now()
  where not is_suspended
    and (last_listings_digest_sent_at is null or last_listings_digest_sent_at < now() - interval '20 hours');

  return v_count;
end;
$$;

select cron.schedule(
  'new-listings-digest-daily',
  '0 17 * * *',
  $$select public.send_new_listings_digest()$$
);

-- Same posture as send_buzz_digest() -- pg_cron only, never PostgREST.
revoke execute on function public.send_new_listings_digest() from public, anon, authenticated;

-- =========================================================================
-- 5. Inactivity win-back -- a bounded window, not "inactive forever", so
-- this fires once as someone crosses the threshold rather than nagging
-- daily for as long as they stay away.
-- =========================================================================

create or replace function public.send_winback_notifications()
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  v_count integer;
begin
  insert into public.notifications (recipient_id, type, title, body, actor_id, actor_name, link_url)
  select
    p.id,
    'winback',
    'We miss you 👋',
    'New hostels, Buzz posts, and marketplace listings since you last checked in.',
    null,
    'Campa',
    '/'
  from public.profiles p
  where not p.is_suspended
    and p.last_active_at is not null
    and p.last_active_at between now() - interval '5 days' and now() - interval '3 days'
    and (p.last_winback_sent_at is null or p.last_winback_sent_at < now() - interval '6 days');

  get diagnostics v_count = row_count;

  update public.profiles
  set last_winback_sent_at = now()
  where not is_suspended
    and last_active_at is not null
    and last_active_at between now() - interval '5 days' and now() - interval '3 days'
    and (last_winback_sent_at is null or last_winback_sent_at < now() - interval '6 days');

  return v_count;
end;
$$;

select cron.schedule(
  'winback-daily',
  '0 10 * * *',
  $$select public.send_winback_notifications()$$
);

-- Same posture as send_buzz_digest() -- pg_cron only, never PostgREST.
revoke execute on function public.send_winback_notifications() from public, anon, authenticated;

notify pgrst, 'reload schema';
